version: 0.1.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore Acme.net.sln
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test_script:
- dotnet test .\src\Oocx.Acme.Tests
- dotnet test .\src\Oocx.Pkcs.Tests
artifacts:
- path: src\Oocx.Acme.Console\bin\Debug\net461\acme.exe
- path: '**\*.nupkg'

deploy:
- provider: GitHub
  auth_token:
    secure: +xbvoITYPaEgmN7KE7yzVuwhiZgqZ4OwlUWPvG/YmiX+yZS0UU57b8te3qRb9Ayv
  artifact: src\Oocx.Acme.Console\bin\Debug\net461\acme.exe
  draft: true
- provider: NuGet
  api_key:
    secure: fHwi4jYY65gWfM9aXQlgsvRldB5a/hfr9ifRQqVkrJw+Hd4osewjEad16Rr+AOYS